version: "3.9"
services:
  backend:
    build: ./backend
    container_name: stockcorr-backend
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      # Set your production origins (comma-separated). Example:
      # - ALLOW_ORIGINS=https://stock.nethercot.uk,https://api.stock.nethercot.uk
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: stockcorr-frontend
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
